In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data_original = pd.read_csv('/content/DataPreprocessingGraded_dataset (2).csv')

In [ ]:
data_original

V1    V2       V3    V4        V5 Target
0     2.0  50.0  12500.0  98.0  NEGATIVE    YES
1     0.0  13.0   3250.0  28.0  NEGATIVE    YES
2       ?     ?   4000.0  35.0  NEGATIVE    YES
3       ?  20.0   5000.0  45.0  NEGATIVE    YES
4     1.0  24.0   6000.0  77.0  NEGATIVE     NO
..    ...   ...      ...   ...       ...    ...
743  23.0   2.0    500.0  38.0  NEGATIVE     NO
744  21.0   2.0    500.0  52.0  NEGATIVE     NO
745  23.0   3.0    750.0  62.0  NEGATIVE     NO
746  39.0   1.0    250.0  39.0  NEGATIVE     NO
747  72.0   1.0    250.0  72.0  NEGATIVE     NO

[748 rows x 6 columns]

In [ ]:
data = data_original.copy()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      748 non-null    object 
 1   V2      748 non-null    object 
 2   V3      748 non-null    float64
 3   V4      748 non-null    float64
 4   V5      748 non-null    object 
 5   Target  748 non-null    object 
dtypes: float64(2), object(4)
memory usage: 35.2+ KB


In [ ]:
y_data = data.pop('Target')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      748 non-null    object 
 1   V2      748 non-null    object 
 2   V3      748 non-null    float64
 3   V4      748 non-null    float64
 4   V5      748 non-null    object 
dtypes: float64(2), object(3)
memory usage: 29.3+ KB


In [ ]:
data.V1.unique()

array(['2.0', '0.0', '?', '1.0', '4.0', '5.0', '9.0', '3.0', '12.0',
       '6.0', '11.0', '10.0', '13.0', '8.0', '14.0', '7.0', '16.0',
       '15.0', '23.0', '21.0', '18.0', '22.0', '26.0', '35.0', '38.0',
       '40.0', '74.0', '20.0', '17.0', '25.0', '39.0', '72.0'],
      dtype=object)

In [ ]:
data.V2.unique()

array(['50.0', '13.0', '?', '20.0', '24.0', '12.0', '9.0', '46.0', '3.0',
       '10.0', '6.0', '5.0', '14.0', '11.0', '8.0', '16.0', '7.0', '2.0',
       '19.0', '4.0', '17.0', '1.0', '15.0', '22.0', '18.0', '38.0',
       '43.0', '34.0', '44.0', '26.0', '41.0', '21.0', '33.0'],
      dtype=object)

In [ ]:
data.V5.unique()

array(['NEGATIVE'], dtype=object)

In [ ]:
data.replace("?",np.nan,inplace=True)

In [ ]:
data

V1    V2       V3    V4        V5
0     2.0  50.0  12500.0  98.0  NEGATIVE
1     0.0  13.0   3250.0  28.0  NEGATIVE
2     NaN   NaN   4000.0  35.0  NEGATIVE
3     NaN  20.0   5000.0  45.0  NEGATIVE
4     1.0  24.0   6000.0  77.0  NEGATIVE
..    ...   ...      ...   ...       ...
743  23.0   2.0    500.0  38.0  NEGATIVE
744  21.0   2.0    500.0  52.0  NEGATIVE
745  23.0   3.0    750.0  62.0  NEGATIVE
746  39.0   1.0    250.0  39.0  NEGATIVE
747  72.0   1.0    250.0  72.0  NEGATIVE

[748 rows x 5 columns]

In [ ]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values=np.nan,strategy='mean')
data['V1'] = si.fit_transform(np.array([data['V1']]).reshape(-1,1))
data['V2'] = si.fit_transform(np.array([data['V2']]).reshape(-1,1))

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

In [ ]:
data['V5'] = oe.fit_transform(np.array(data['V5']).reshape(-1,1))

In [ ]:
data

V1         V2       V3    V4   V5
0     2.000000  50.000000  12500.0  98.0  0.0
1     0.000000  13.000000   3250.0  28.0  0.0
2     9.562584   5.464334   4000.0  35.0  0.0
3     9.562584  20.000000   5000.0  45.0  0.0
4     1.000000  24.000000   6000.0  77.0  0.0
..         ...        ...      ...   ...  ...
743  23.000000   2.000000    500.0  38.0  0.0
744  21.000000   2.000000    500.0  52.0  0.0
745  23.000000   3.000000    750.0  62.0  0.0
746  39.000000   1.000000    250.0  39.0  0.0
747  72.000000   1.000000    250.0  72.0  0.0

[748 rows x 5 columns]

In [ ]:
num_data = data.iloc[:,:4]

In [ ]:
num_data

V1         V2       V3    V4
0     2.000000  50.000000  12500.0  98.0
1     0.000000  13.000000   3250.0  28.0
2     9.562584   5.464334   4000.0  35.0
3     9.562584  20.000000   5000.0  45.0
4     1.000000  24.000000   6000.0  77.0
..         ...        ...      ...   ...
743  23.000000   2.000000    500.0  38.0
744  21.000000   2.000000    500.0  52.0
745  23.000000   3.000000    750.0  62.0
746  39.000000   1.000000    250.0  39.0
747  72.000000   1.000000    250.0  72.0

[748 rows x 4 columns]

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline,FeatureUnion
from sklearn.feature_selection import VarianceThreshold
from sklearn.compose import ColumnTransformer


steps1 = ColumnTransformer([('Impute',SimpleImputer(missing_values=np.nan,strategy='mean'),[0,1,2,3])])
                           #('Scaler',StandardScaler(),[0,1,2,3])])
steps2 = ColumnTransformer([('Scaler',StandardScaler(),[0,1,2,3])])

steps3 = ColumnTransformer([('Encoder',OrdinalEncoder(),[4])])

In [ ]:
pipe1 = Pipeline([('Numerical1',steps1),('Category1',StandardScaler())])
pipe2 = FeatureUnion([('Numeric2',pipe1),('Category2',steps3)])

In [ ]:
pipe2

FeatureUnion(transformer_list=[('Numeric2',
                                Pipeline(steps=[('Numerical1',
                                                 ColumnTransformer(transformers=[('Impute',
                                                                                  SimpleImputer(),
                                                                                  [0,
                                                                                   1,
                                                                                   2,
                                                                                   3])])),
                                                ('Category1',
                                                 StandardScaler())])),
                               ('Category2',
                                ColumnTransformer(transformers=[('Encoder',
                                                                 OrdinalEncoder(),
                                                                 [4])]))])

In [ ]:
col = ['V1','V2','V3','V4','V5']

In [ ]:
fghj = pipe2.fit_transform(data)

In [ ]:
data5 = pd.DataFrame(fghj,columns=col)

In [ ]:
data5

V1            V2        V3        V4   V5
0   -0.938169  7.709867e+00  7.623346  2.615633  0.0
1   -1.186278  1.304549e+00  1.282738 -0.257881  0.0
2    0.000000 -1.537585e-16  1.796842  0.029471  0.0
3    0.000000  2.516366e+00  2.482313  0.439973  0.0
4   -1.062223  3.208833e+00  3.167784  1.753579  0.0
..        ...           ...       ...       ...  ...
743  1.666966 -5.997340e-01 -0.602307  0.152621  0.0
744  1.418858 -5.997340e-01 -0.602307  0.727324  0.0
745  1.666966 -4.266173e-01 -0.430940  1.137826  0.0
746  3.651831 -7.728506e-01 -0.773675  0.193671  0.0
747  7.745616 -7.728506e-01 -0.773675  1.548328  0.0

[748 rows x 5 columns]

In [ ]:
pipe3 = Pipeline([('1st',pipe2),('2nd',VarianceThreshold(threshold=0.1))])

In [ ]:
pipe3

Pipeline(steps=[('1st',
                 FeatureUnion(transformer_list=[('Numeric2',
                                                 Pipeline(steps=[('Numerical1',
                                                                  ColumnTransformer(transformers=[('Impute',
                                                                                                   SimpleImputer(),
                                                                                                   [0,
                                                                                                    1])])),
                                                                 ('Category1',
                                                                  StandardScaler())])),
                                                ('Category2',
                                                 ColumnTransformer(transformers=[('Encoder',
                                                                                  OrdinalEncoder(),
                                                                                  [4])]))])),
                ('2nd', VarianceThreshold(threshold=0.1))])

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
estimator = LogisticRegression()
selector = RFE(estimator, n_features_to_select = 2, step=1)

In [ ]:
pipe4 = pipe3 = Pipeline([('1st',pipe2),('2nd',selector)])

In [ ]:
pipe4

Pipeline(steps=[('1st',
                 FeatureUnion(transformer_list=[('Numeric2',
                                                 Pipeline(steps=[('Numerical1',
                                                                  ColumnTransformer(transformers=[('Impute',
                                                                                                   SimpleImputer(),
                                                                                                   [0,
                                                                                                    1,
                                                                                                    2,
                                                                                                    3])])),
                                                                 ('Category1',
                                                                  StandardScaler())])),
                                                ('Category2',
                                                 ColumnTransformer(transformers=[('Encoder',
                                                                                  OrdinalEncoder(),
                                                                                  [4])]))])),
                ('2nd',
                 RFE(estimator=LogisticRegression(), n_features_to_select=2))])

In [ ]:
gh = pipe4.fit_transform(data,y_data)
selector.support_

array([ True, False,  True, False, False])

In [ ]:
pipe3.fit_transform(data)

TypeError: ignored

In [ ]:
pipe3.fit_transform(data)

In [ ]:
pipe4 = Pipeline([('Numerical',pipe2),('Variance',VarianceThreshold(threshold=0.1))])

In [ ]:
pipe3

Pipeline(steps=[('Numerical',
                 FeatureUnion(transformer_list=[('Numeric',
                                                 Pipeline(steps=[('Numerical',
                                                                  ColumnTransformer(transformers=[('Impute',
                                                                                                   SimpleImputer(),
                                                                                                   [0,
                                                                                                    1,
                                                                                                    2,
                                                                                                    3])])),
                                                                 ('Category',
                                                                  ColumnTransformer(transformers=['Scaler',
                                                                                                  StandardScaler()]))])),
                                                ('Category',
                                                 ColumnTransformer(transformers=[('Encoder',
                                                                                  OrdinalEncoder(),
                                                                                  [4])]))])),
                ('Variance', VarianceThreshold(threshold=0.1))])

In [ ]:
pipe3 = FeatureUnion([('Numerical',pipe1,),('Category',pipe2)])

In [ ]:
full_pipe = Pipeline([('FeatureUnion',pipe3),('Variance',VarianceThreshold(threshold=0.1))])

In [ ]:
full_pipe

Pipeline(steps=[('FeatureUnion',
                 FeatureUnion(transformer_list=[('Numerical',
                                                 Pipeline(steps=[('Impute',
                                                                  SimpleImputer()),
                                                                 ('Scaler',
                                                                  StandardScaler())])),
                                                ('Category',
                                                 Pipeline(steps=[('Encoder',
                                                                  OrdinalEncoder())]))])),
                ('Variance', VarianceThreshold(threshold=0.1))])

In [ ]:
from sklearn.feature_selection import SequentialFeatureSelector

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
data_original['Target'] = oe.fit_transform(np.array(data_original['Target']).reshape(-1,1))

In [ ]:
y_data = data_original['Target']

In [ ]:
estimator = LogisticRegression()
sfs = SequentialFeatureSelector(estimator, n_features_to_select=2,direction="backward")
sfs.fit_transform(data5,y_data)

array([[ 7.62334626,  2.61563344],
       [ 1.28273826, -0.2578809 ],
       [ 1.79684161,  0.02947053],
       ...,
       [-0.43093957,  1.13782607],
       [-0.77367514,  0.19367135],
       [-0.77367514,  1.54832812]])

In [ ]:
pipe5 =  Pipeline([('1st',pipe2),('2nd',sfs)])

In [ ]:
pipe5

Pipeline(steps=[('1st',
                 FeatureUnion(transformer_list=[('Numeric2',
                                                 Pipeline(steps=[('Numerical1',
                                                                  ColumnTransformer(transformers=[('Impute',
                                                                                                   SimpleImputer(),
                                                                                                   [0,
                                                                                                    1,
                                                                                                    2,
                                                                                                    3])])),
                                                                 ('Category1',
                                                                  StandardScaler())])),
                                                ('Category2',
                                                 ColumnTransformer(transformers=[('Encoder',
                                                                                  OrdinalEncoder(),
                                                                                  [4])]))])),
                ('2nd',
                 SequentialFeatureSelector(direction='backward',
                                           estimator=LogisticRegression(),
                                           n_features_to_select=2))])

In [ ]:
print(sfs.get_support())

[False False  True  True False]


In [ ]:
import numpy as np

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OrdinalEncoder
from sklearn.feature_selection import VarianceThreshold
from sklearn.compose import ColumnTransformer

In [ ]:
from sklearn.pipeline import Pipeline,FeatureUnion

In [ ]:
trans1 = ColumnTransformer([('impute',SimpleImputer(missing_values=np.nan,strategy='mean'),[0,1,2,3])])
#trans2 = ColumnTransformer(['Scaler',StandardScaler(),[2,3]])
combine = Pipeline(steps=[('Numeric1',trans1),
                         ('Numeric2',StandardScaler())])
#combine.fit_transform(data)
trans3 = ColumnTransformer([('cat',OrdinalEncoder(),[4])])
complete = FeatureUnion([('numeric',combine),('category',trans3)])

pipe = Pipeline(steps=[('cp',complete),('variance',VarianceThreshold(threshold=0.1))])

pipe.fit_transform(data)

array([[-9.38169390e-01,  7.70986653e+00,  7.62334626e+00,
         2.61563344e+00],
       [-1.18627754e+00,  1.30454949e+00,  1.28273826e+00,
        -2.57880900e-01],
       [ 0.00000000e+00, -1.53758496e-16,  1.79684161e+00,
         2.94705348e-02],
       ...,
       [ 1.66696622e+00, -4.26617275e-01, -4.30939574e-01,
         1.13782607e+00],
       [ 3.65183145e+00, -7.72850628e-01, -7.73675141e-01,
         1.93671355e-01],
       [ 7.74561598e+00, -7.72850628e-01, -7.73675141e-01,
         1.54832812e+00]])

In [ ]:
pipe

Pipeline(steps=[('cp',
                 FeatureUnion(transformer_list=[('numeric',
                                                 Pipeline(steps=[('Numeric1',
                                                                  ColumnTransformer(transformers=[('impute',
                                                                                                   SimpleImputer(),
                                                                                                   [0,
                                                                                                    1,
                                                                                                    2,
                                                                                                    3])])),
                                                                 ('Numeric2',
                                                                  StandardScaler())])),
                                                ('category',
                                                 ColumnTransformer(transformers=[('cat',
                                                                                  OrdinalEncoder(),
                                                                                  [4])]))])),
                ('variance', VarianceThreshold(threshold=0.1))])

In [ ]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LogisticRegression
trans4 = SequentialFeatureSelector(estimator=LogisticRegression(),n_features_to_select=2)

In [ ]:
trans4.fit(complete.fit_transform(data),y_data)

SequentialFeatureSelector(estimator=LogisticRegression(),
                          n_features_to_select=2)

In [ ]:
trans4.support_

array([False,  True, False,  True, False])